# Generated by Django 4.2.1 on 2023-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(default='0', max_length=11, verbose_name='Account No')),
                ('tr_amount', models.DecimalField(decimal_places=2, default='0', max_digits=20, verbose_name='Amount to Transfer')),
                ('balan', models.DecimalField(decimal_places=2, default='0', max_digits=20, verbose_name='Balance')),
                ('d_t', models.DateTimeField(default='0', verbose_name='Transaction Date')),
                ('to_acc', models.CharField(default='0', max_length=11, verbose_name='To Account')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='0', max_length=6, verbose_name='USER ID')),
                ('acc_no', models.CharField(default='0', max_length=11, verbose_name='Account No')),
                ('first_name', models.CharField(default='0', max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(default='0', max_length=100, null=True, verbose_name='Last Name')),
                ('dob', models.DateField(default='0', null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(default='0', max_length=1, verbose_name='Gender')),
                ('password', models.CharField(default='0', max_length=20, verbose_name='PASSWORD')),
                ('ifsc', models.CharField(default='0', max_length=50, verbose_name='IFSC')),
                ('acc_type', models.CharField(default='0', max_length=50, verbose_name='Account Type')),
                ('balan', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('phone', models.CharField(default='0', max_length=10, verbose_name='Phone No')),
                ('email', models.EmailField(default='0', max_length=254, verbose_name='Email Id')),
                ('location', models.CharField(default='0', max_length=100, verbose_name='Location')),
                ('loan', models.CharField(default='one', max_length=50, null=True, verbose_name='Type of Loans')),
                ('cr_type', models.CharField(default='one', max_length=50, null=True, verbose_name='Card Type')),
            ],
        ),
    ]
