# Generated by Django 4.2.1 on 2023-08-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.CharField(default=0, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default=0, max_length=250)),
                ('ph1', models.CharField(default=0, max_length=250)),
                ('ph2', models.CharField(default=0, max_length=250)),
                ('ph3', models.CharField(default=0, max_length=250)),
                ('lp', models.CharField(default=0, max_length=250)),
                ('em', models.CharField(default=0, max_length=250)),
            ],
        ),
    ]
