# Generated by Django 4.2.1 on 2023-08-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_complaint_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='comp',
            new_name='com_letter',
        ),
    ]
